### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by thakur24** [thakur24/hello-world#30]
Trying to prepare a document listing the best resources to learn C and JAVA .

**Comment by bhu800** [comment]
I want to work on it

**Comment by bestorw01** [comment]
I want to contribute to this

**Comment by jenniferafelton** [comment]
Can I fix your README to be a little more readable?

**Comment by thakur24** [comment]
Sure ! Go ahead.

**Comment by ichromanrd** [comment]
Does the aim is only to provide resources for learning C and Java? Does link url to resource allowed?
